### ISSUE TITLE
Verify BatteryFaults Correctness

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Hermes#27]
So the batteryfaults data in the protocol was updated: The limit flags should have been put into index 4 of the payload instead of 5 (That was the cause of the test tool issue we've been having since the summer). Check if Hermes has that error as well, and if so fix it.

**Comment by nathanaelhuh** [comment]
Hermes has this error as well. I found it in CommunicationLayer/MessagingFramework/BatteryFaultsMessage.cpp
