### ISSUE TITLE
Issues I found during Data Sanity

### ISSUE THREAD

**Issue by nathanaelhuh** [UCSolarCarTeam/Epsilon-Hermes#29]
Some of these are somewhat irrelevant and are more for looking it better and checking it easier in the future. *'s are for issues I'm not sure of (aka for someone who knows the code better than me aka Bill or Enoch)

~~Move Aux to below reset
[`BusinessLayer/JsonForwarder/JsonDefines.h`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/BusinessLayer/JsonForwarder/JsonDefines.h)
Line 50~~

[`BusinessLayer/JsonForwarder/JsonDefines.h`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/BusinessLayer/JsonForwarder/JsonDefines.h)
Not nessesary but if possible, change lines to match up with communications protocol
Motor Faults

~~Switch left and right (not sure of impact of it though)
[`BusinessLayer/JsonMessageBuilder/JsonMessageBuilder.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/BusinessLayer/JsonMessageBuilder/JsonMessageBuilder.cpp)
Line 139, 140
Also move aux from music to driver inputs~~

~~Back EMF Imaginary shouldn't exist
[`CommunicationLayer/DataPopulators/MotorDetailsPopulator.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/DataPopulators/MotorDetailsPopulator.cpp)
Line 20~~

~~Limit Flag offset
[`CommunicationLayer/MessagingFramework/BatteryFaultsMessage.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/BatteryFaultsMessage.cpp)
Line 10: should be 4, not 5~~

~~Spelling Error
[`CommunicationLayer/MessagingFramework/BatteryMessage.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/BatteryMessage.cpp)
Line 11, 54: cells spelt wrong~~

~~Offsets are off set
[`CommunicationsLayer/MessagingFramework/BatteryMessage.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/BatteryMessage.cpp)
Lines 30-34 are off, refer to communications protocol~~

~~[`CommunicationsLayer/MessagingFramework/MessageDefines.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/MessageDefines.cpp)
I think it's supposed to match package sizes with or without metadata, I'm not sure but either way it's wrong~~

~~Back EMF Imaginary
[`CommunicationsLayer/MessagingFramework/MotorDetailsMessage.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/MotorDetailsMessage.cpp)
Line 19, 45: has Back EMF Imaginary~~

~~Variable names confusing and maybe wrong~~
[`CommunicationsLayer/MessagingFramework/MotorDetailsMessage.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/MotorDetailsMessage.cpp)
~~Lines 21 and 22: other times has been just 3 and 1, not 33 and 19. Since no decimal, makes it confusing and mismatched~~

~~Mistype
[`CommunicationsLayer/MessagingFramework/MotorDetailsMessage.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/MotorDetailsMessage.cpp)
Line 40: Should be = not -~~

~~Back EMF Imaginary
[`CommunicationsLayer/MessagingFramework/MotorDetailsMessage.h`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/CommunicationLayer/MessagingFramework/MotorDetailsMessage.h)
Line 19~~

~~Aux in Music
[`DataLayer/DriverControlsData/DriverControlsData.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/DataLayer/DriverControlsData/DriverControlsData.cpp)
Line 13
~~Also missing the preceeding 0~~
Line 83, getter needs to be changed and moved~~

~~Style change
Move aux to below reset
[`DataLayer/DriverControlsData/DriverControlsData.h`
](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/DataLayer/DriverControlsData/DriverControlsData.h)Same for FakeDriverControlsData.h
Same for I_DriverControlsData.h~~

~~Back EMF Imaginary in all [`DataLayer/MotorDetailsData`](`DataLayer/MotorDetailsData`)
[`DataLayer/MotorDetailsData/FakeMotorDetailUnit.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/blob/master/DataLayer/MotorDetailsData/FakeMotorDetailsUnit.cpp)
Lines 53-56, 112
Note: don't forget the delete the getters and setters as well~~
[
`DataLayer/MpptData/Fake`](https://github.com/UCSolarCarTeam/Epsilon-Hermes/tree/master/DataLayer/MpptData) files have nothing

**Comment by bill-luu** [comment]
> Limit Flag offset
CommunicationLayer/MessagingFramework/BatteryFaultsMessage.cpp
Line 10: should be 4, not 5

> Offsets are off set
CommunicationsLayer/MessagingFramework/BatteryMessage.cpp
Lines 30-34 are off, refer to communications protocol

> CommunicationsLayer/MessagingFramework/MessageDefines.cpp
I think it's supposed to match package sizes with or without metadata, I'm not sure but either way it's wrong

> Aux in Music
DataLayer/DriverControlsData/DriverControlsData.cpp

Took a quick look, the above quoted represent actual mistakes, and should be fixed asap.

The rest are stylistic changes that would be nice to change.

**Comment by bill-luu** [comment]
> Aux in Music
DataLayer/DriverControlsData/DriverControlsData.cpp
Line 13
Also missing the preceding 0

Preceding 0s isn't necessary.
