### ISSUE TITLE
DataForwarded Test fails occasionally

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Hermes#60]
Try to run the Tests:
`for run in {1..30}; do ./Tests || break; done`

Occasionally, the `DataForwarded` Test fails

**Comment by bill-luu** [comment]
Consider the `AtLeast(n)` cardinality:
https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md

**Comment by mglyngberg** [comment]
Forgot to close this when it was fixed in #64
