### ISSUE TITLE
Hermes fails if log folder is not in the build directory

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Hermes#66]
If there is no `log` folder in the build directory, a "Logging initalization failed" error will occur.

Expected behavior: 
If there is no log folder, there should be one created instead of it crashing.

See how it's [being handled in the dashboard](https://github.com/UCSolarCarTeam/Epsilon-Dashboard/blob/master/src/CommunicationLayer/Logging/Logging.cpp)

**Comment by mglyngberg** [comment]
Addressed in #69
